#!/bin/bash
set -eu

if [[ $# -ne 2 ]]; then
    echo "Usage; $0 SUB SES, e.g. HCA9953406 V1"
    exit 1
fi

/cloud/downloadcmd-auther
downloadcmd --username $NDA_USERNAME \
            --package $NDA_PACKAGE \
            --file-regex datastructure_manifest

/cloud/list-rapidtide-relevant-images \
    --participant $1 \
    --session $2 \
> /s3-files-requested

downloadcmd --package $NDA_PACKAGE \
            --username $NDA_USERNAME \
            --txt /s3-files-requested \
            --directory /data_in 

# fix filenames broken by NDA until https://github.com/NDAR/nda-tools/issues/88 resolved
find /data_in -type f -name '*_1.*' | while read fname; do mv "$fname" "${fname/_1/}"; done
find /data_in -type f -name '*_2.*' | while read fname; do mv "$fname" "${fname/_2/}"; done
