#!/bin/csh -f
#
#   Copyright 2016-2021 Blaise Frederick
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#
cp tmp/rapidtide2x_phase2output_MTT.nii.gz testtargets/rapidtide2x_phase2target_MTT.nii.gz
cp tmp/rapidtide2x_phase2output_lagmask.nii.gz testtargets/rapidtide2x_phase2target_lagmask.nii.gz
cp tmp/rapidtide2x_phase2output_lagsigma.nii.gz testtargets/rapidtide2x_phase2target_lagsigma.nii.gz
cp tmp/rapidtide2x_phase2output_lagstrengths.nii.gz testtargets/rapidtide2x_phase2target_lagstrengths.nii.gz
cp tmp/rapidtide2x_phase2output_lagtimes.nii.gz testtargets/rapidtide2x_phase2target_lagtimes.nii.gz

