#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#   Copyright 2016-2026 Blaise Frederick
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#
import argparse
from typing import Any

import rapidtide.io as tide_io
import rapidtide.maskutil as tide_mask
import rapidtide.workflows.parser_funcs as pf


def _get_parser() -> Any:
    """
    Argument parser for aparcaseg2dseg.

    This function constructs and returns an `argparse.ArgumentParser` object configured
    with all the necessary arguments for the `aparcaseg2dseg` utility. It supports parsing
    of NIfTI atlas files, with options for transforming, splitting, masking, and
    reformatting atlas data.

    Returns
    -------
    argparse.ArgumentParser
        Configured argument parser for aparcaseg2dseg.

    Notes
    -----
    The parser includes both required and optional arguments for handling NIfTI files,
    including support for 3D and 4D output formats, splitting regions along the midline,
    applying masks, and debugging options.

    """
    parser = argparse.ArgumentParser(
        prog="aparcaseg2dseg",
        description="A utility to generate wm parcellation files from a FreeSurfer aparc+aseg file",
        allow_abbrev=False,
    )

    # Required arguments
    pf.addreqinputniftifile(
        parser,
        "aparcasegname",
        addedtext="Must be a 3D aparc+aseg file generated by freesurfer",
    )
    pf.addreqoutputniftifile(parser, "dsegname")
    
    debugging = parser.add_argument_group("Debugging options")
    debugging.add_argument(
        "--debug",
        dest="debug",
        action="store_true",
        help="Output debugging information",
        default=False,
    )
    return parser


def aparcaseg2dseg(args: Any) -> None:
    """
    Process and convert aparc+aseg files for neuroimaging analysis.

    This function reads a template NIfTI file, reshapes it into a 4D array, and optionally
    splits left-right regions, resamples to a target resolution, applies a mask, and saves
    the processed data as a new NIfTI file. It supports both 3D and 4D input templates,
    and can handle label files for region mapping.

    Parameters
    ----------
    args : Any
        An object containing command-line arguments. Expected attributes include:
        - aparcasegname : str
            Path to the input NIfTI aparc+aseg file.
        - dsegname : str
            Root name of the output NIfTI dseg file.
        - debug : bool
            If True, print debug information.

    Returns
    -------
    None
        This function does not return a value but saves processed data to disk.

    Notes
    -----
    - The function supports both 3D and 4D input templates.
    - If `targetfile` is provided, the template is resampled using FSL or ANTs.
    - If `maskfile` is not provided, a mask is generated from the template using
      `maskthresh`.
    - Labels from `labelfile` are used in the output if provided.

    """
    if args.debug:
        print(args)

    print("loading aparc+aseg data")

    (
        aparcaseg_img,
        aparcaseg_data,
        aparcaseg_hdr,
        aparcasegdims,
        aparcasegsizes,
    ) = tide_io.readfromnifti(args.aparcasegname)
    xsize, ysize, numslices, timepoints = tide_io.parseniftidims(aparcasegdims)
    numspatiallocs = int(xsize) * int(ysize) * int(numslices)

    thegraymask = tide_mask.readamask(
        args.aparcasegname,
        aparcaseg_hdr,
        numspatiallocs,
        valslist=tide_io.colspectolist("APARC_GRAY"),
        maskname="gray matter",
    )
    thewhitemask = tide_mask.readamask(
        args.aparcasegname,
        aparcaseg_hdr,
        numspatiallocs,
        valslist=tide_io.colspectolist("APARC_WHITE"),
        maskname="white matter",
    )
    thecsfmask = tide_mask.readamask(
        args.aparcasegname,
        aparcaseg_hdr,
        numspatiallocs,
        valslist=tide_io.colspectolist("APARC_CSF"),
        maskname="CSF",
    )
    dsegdata = thegraymask + 2 * thewhitemask + 3 * thecsfmask
    tide_io.savetonifti(
        dsegdata,
        aparcaseg_hdr,
        args.dsegname,
    )