#!/usr/bin/env python
import numpy as np
import matplotlib.pyplot as plt
from rapidtide.tide_funcs import complex_cepstrum
#from acoustics.cepstrum import complex_cepstrum

duration = 5.0
fs = 8000.0
samples = int(fs*duration)
t = np.arange(samples) / fs

fundamental = 100.0
harmonics = np.arange(1, 30) * fundamental
signal = np.sin(2.0*np.pi*harmonics[:,None]*t).sum(axis=0)
ceps, _ = complex_cepstrum(signal)

fig = plt.figure()
ax0 = fig.add_subplot(211)
ax0.plot(t, signal)
ax0.set_xlabel('time in seconds')
ax0.set_xlim(0.0, 0.05)
ax1 = fig.add_subplot(212)
ax1.plot(t, ceps)
ax1.set_xlabel('quefrency in seconds')
ax1.set_xlim(0.005, 0.015)
ax1.set_ylim(-5., +10.)
plt.show()
