#!/bin/bash

#chmod -R u+rx build	# I don't know why I have to do this now, but I do
rm -rf build dist rapidtide.egg-info __pycache__ */__pycache__ */*/__pycache__

pipresult="True"

while [ -n "$pipresult" ]
do
    pipresult=`pip uninstall -y rapidtide | grep "Found existing"`
    if [[ -z $pipresult ]]
    then
        echo No installations found - quitting.
        break
    else
        echo "$pipresult" - removing.
    fi
done
