#!/bin/bash

conda create --name rapidtide
conda activate rapidtide
conda install nomkl 'numpy>=1.16' scipy matplotlib pandas statsmodels scikit-learn nibabel pyfftw numba pyqt 'pyqtgraph>=0.11' tensorflow keras

