#!/bin/bash

conda create --name rapidtide python==3.11
conda activate rapidtide
conda install \
    numpy \
    scipy \
    matplotlib \
    pandas \
    statsmodels \
    scikit-learn \
    scikit-image \
    nibabel \
    nilearn \
    pyfftw \
    pywavelets \
    pyqt \
    pyqt5-sip \
    pyqtgraph \
    tqdm

pip install tensorflow keras
