#!/usr/bin/env python
import json
import requests
import tomlkit
import io


def getcontribinfo(theurl):
    content = requests.get(theurl)
    data = json.loads(content.content)
    try:
        thename = data['name']
    except KeyError:
        return None
    else:
        return thename
    

theurl = 'https://api.github.com/repos/bbfrederick/rapidtide/contributors?anon=1'
content = requests.get(theurl)
data = json.loads(content.content)
print(data)

contriblist = []
for theitem in data:
    print(theitem)
    try:
        contriburl = theitem['url']
    except KeyError:
        pass
    else:
        thename = getcontribinfo(contriburl)
        if thename is not None:
            contriblist.append({"name": thename})
            #print(contriburl, getcontribinfo(contriburl))

with open("pyproject.toml") as stream:
    try:
        pyproject_loaded = tomlkit.load(stream)
    except tomlkit.TOMLError as exc:
        print(exc)


# remove the existing authors field
pyproject_loaded["project"].pop("authors")

# create a properly formatted contriblist
authoritem = tomlkit.array()
for contrib in contriblist:
    authoritem.add_line(contrib)
authoritem.add_line(indent="")
print(authoritem.as_string())

# now add it
pyproject_loaded["project"]["authors"] = authoritem



# Write TOML file
with io.open('test.toml', 'w', encoding='utf8') as outfile:
    tomlkit.dump(pyproject_loaded, outfile)
