#!/bin/bash

mamba update \
    numpy \
    scipy \
    matplotlib>=3.3.0 \
    pandas \
    statsmodels \
    scikit-learn \
    scikit-image \
    nibabel \
    nilearn \
    numba \
    pywavelets \
    pyqt \
    pyqt5-sip \
    pyqtgraph>=0.12.0 \
    tqdm

#pip install tensorflow keras
