#!/usr/bin/env python

import json

territoryvols = [
    154557,
    153171,
    8970,
    8724,
    23927,
    24573,
    197823,
    192734,
    101551,
    104636,
    127844,
    124444,
    33473,
    27467,
    11888,
    12167,
    19995,
    18577,
    109971,
    104433,
    20714,
    19338,
    8331,
    8509,
    18403,
    18499,
    36355,
    36978,
    69535,
    71377
]

hierdict = {}

# put the territory sizes in the dictionary
for territory in range(len(territoryvols)):
    hierdict[f"territory_{territory + 1}_size"] = territoryvols[territory]

# now the branch info
region = 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([19,20,13,14,17,18,11,12,7,8,1,2,9,10,3,4,15,16,23,24])
hierdict[regionname]["right"] = sorted([27,28,29,30,5,6,25,26,21,22])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([19,20,13,14,17,18,11,12,7,8,1,2,9,10])
hierdict[regionname]["right"] = sorted([3,4,15,16,23,24])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([3,4])
hierdict[regionname]["right"] = sorted([15,16,23,24])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([19,20,13,14])
hierdict[regionname]["right"] = sorted([17,18,11,12,7,8,1,2,9,10])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([17,18,11,12])
hierdict[regionname]["right"] = sorted([7,8,1,2,9,10])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([27,28,29,30])
hierdict[regionname]["right"] = sorted([5,6,25,26,21,22])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([15,16])
hierdict[regionname]["right"] = sorted([23,24])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([5,6])
hierdict[regionname]["right"] = sorted([25,26,21,22])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([7,8])
hierdict[regionname]["right"] = sorted([1,2,9,10])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([17,18])
hierdict[regionname]["right"] = sorted([11,12])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([25,26])
hierdict[regionname]["right"] = sorted([21,22])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([1,2])
hierdict[regionname]["right"] = sorted([9,10])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([19,20])
hierdict[regionname]["right"] = sorted([13,14])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([27,28])
hierdict[regionname]["right"] = sorted([29,30])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([27])
hierdict[regionname]["right"] = sorted([28])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([29])
hierdict[regionname]["right"] = sorted([30])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([5])
hierdict[regionname]["right"] = sorted([6])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([25])
hierdict[regionname]["right"] = sorted([26])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([21])
hierdict[regionname]["right"] = sorted([22])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([19])
hierdict[regionname]["right"] = sorted([20])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([13])
hierdict[regionname]["right"] = sorted([14])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([17])
hierdict[regionname]["right"] = sorted([18])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([11])
hierdict[regionname]["right"] = sorted([12])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([7])
hierdict[regionname]["right"] = sorted([8])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([1])
hierdict[regionname]["right"] = sorted([2])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([9])
hierdict[regionname]["right"] = sorted([10])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([3])
hierdict[regionname]["right"] = sorted([4])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([15])
hierdict[regionname]["right"] = sorted([16])
region += 1
regionname = f"branch_{region}"
hierdict[regionname] = {}
hierdict[regionname]["left"] = sorted([23])
hierdict[regionname]["right"] = sorted([24])


for regionname in hierdict.keys():
    if regionname.find("branch") != -1:
        for side in ["left", "right"]:
            territorylist = hierdict[regionname][side]
            totalvoxels = 0
            for territory in territorylist:
                totalvoxels += territoryvols[territory - 1]
            hierdict[regionname][f"{side}_volume"] = totalvoxels

print(hierdict)
        
with open("JHU-ArterialTerritoriesNoVent-LVL1-hierarchy.json", "wb") as fp:
    fp.write(
        json.dumps(hierdict, sort_keys=True, indent=4, separators=(",", ":")).encode(
            "utf-8"
        )
    )
