#!/bin/csh
set numskip=`cat ../examples/src/sim_skip.txt`

rapidtide2 ../examples/src/sim_bolddata_nonoise.nii.gz ../examples/dst/sim_dgsr \
    --numskip=$numskip \
    -N 10000 \
    -L -r -10,10 --refinepasses=3 --lagminthresh=0.5 &

rapidtide2 ../examples/src/sim_bolddata_nonoise.nii.gz ../examples/dst/sim_tHb_lf \
    --numskip=$numskip \
    -N 10000 \
    --regressor=../examples/src/lf_tHb --regressorfreq=12.5 --regressorstart=656.4 \
    -L -r -10,10 &
