#!/bin/csh
rapidtide2 ../testdata/src/filtered_func_data.nii.gz ../testdata/dst/sgsr \
    -F 0.0,0.15 -Z 0.0 &
rapidtide2 ../testdata/src/filtered_func_data.nii.gz ../testdata/dst/dgsr \
    -F 0.0,0.15 --refinepasses=3 &
