#!/bin/csh
rapidtide2 ../examples/src/filtered_func_data.nii.gz ../examples/dst/sgsr \
    -F 0.0,0.15 -Z 0.0 &
rapidtide2 ../examples/src/filtered_func_data.nii.gz ../examples/dst/dgsr \
    -F 0.0,0.15 --refinepasses=3 &
