#!/bin/csh
rapidtide2 ../examples/src/fmri.nii.gz ../examples/dst/sgsr \
    -F 0.0,0.15 -Z 0.0 &
rapidtide2 ../examples/src/fmri.nii.gz ../examples/dst/dgsr \
    -F 0.0,0.15 -r -15,15 --refinepasses=3 &
rapidtide2 ../examples/src/fmri.nii.gz ../examples/dst/dgsr_v2 \
    -F 0.0,0.15 -r -15,15 --refinepasses=3 --lagminthresh=0.5 &
