#!/bin/csh
#
#       $Author: frederic $
#       $Date: 2013/12/17 17:54:46 $
#       $Id: gensimbold,v 1.14 2013/12/17 17:54:46 frederic Exp $
#

set thesourcedir=.
set noiselevel=0.05
set samplerate=12.5
set starttime=656.4
set thbfile=$thesourcedir'/lf_tHb'
set hbofile=$thesourcedir'/lf_HbO'
set hbrfile=$thesourcedir'/lf_HbR'
set fmrifile=$thesourcedir'/fmri.nii.gz'
set numskip=30
set sliceordertype=0	# no slice delay
echo 'simulated NIRS timecourse has a sample rate of '$samplerate' and starts at '$starttime

# pull one volume out of our example bold file to serve as a basis for constructing our dataset
fslroi $fmrifile sim_lags 0 1

set dosubj1='True'
if ( $dosubj1 == 'True' ) then
    # do simsubject1
    # make a 'head' with a mean value of 1000.0 and a matching mask
    fslmaths sim_lags -mul 0.0 -add 1000.0 -roi 16 32 16 32 2 16 0 1 sim_mean.nii.gz
    fslmaths sim_mean.nii.gz -thr 1.0 -bin simmask

    # define an area within the 'head' with a BOLD signal
    fslmaths sim_lags -mul 0.0 -add 1.0 -roi 16 32 16 32 2 16 0 1 sim_boldpc.nii.gz
    
    # define 4 slices with 4 different delay values
    fslmaths sim_lags -mul 0.0 -add  0.0 -roi 16 32 16 32 2 4 0 1 slice1
    fslmaths sim_lags -mul 0.0 -add  4.0 -roi 16 32 16 32 6 4 0 1 slice2
    fslmaths sim_lags -mul 0.0 -add -4.0 -roi 16 32 16 32 10 4 0 1 slice3
    fslmaths sim_lags -mul 0.0 -add  0.0 -roi 16 32 16 32 14 4 0 1 slice4
    fslmaths slice1 -add slice2 -add slice3 -add slice4 sim_lags.nii.gz
    
    simdata $fmrifile sim_mean.nii.gz sim_boldpc.nii.gz sim_lags.nii.gz $hbrfile $samplerate $numskip $starttime sim_boldtemp_HbR $noiselevel $sliceordertype
    simdata $fmrifile sim_mean.nii.gz sim_boldpc.nii.gz sim_lags.nii.gz $thbfile $samplerate $numskip $starttime sim_boldtemp_tHb $noiselevel $sliceordertype
    fslmaths sim_boldtemp_tHb -add sim_boldtemp_HbR -div 2 sim_boldtemp
    fslmaths sim_boldtemp -mul 1.0 sim_bolddata -odt short
    
    echo $starttime > sim_starttime.txt
    echo $samplerate > sim_samplerate.txt
    
    # clean up
    rm slice[1234].nii.gz sim_boldtemp*.nii.gz
    endif
