#!/bin/csh
rapidtide2 fmri.nii.gz ../dst/sgsr \
    -N 10000 \
    -F 0.0,0.15 -Z 0.0 &

rapidtide2 fmri.nii.gz ../dst/dgsr \
    -N 10000 \
    -F 0.0,0.15 -r -7.5,7.5 --refinepasses=3 --lagminthresh=0.5 &

rapidtide2 fmri.nii.gz ../dst/finger_tHb_hf \
    -N 10000 \
    --regressor=lf_tHb --regressorfreq=12.5 --regressorstart=656.4 \
    -F 0.1,0.2 -r -7.5,7.5 &
