#!/usr/bin/env python
from __future__ import print_function
import tide_funcs as tide
import numpy as np

print("starting test")
thepts = np.array([0.95, 0.99, 0.995, 0.999])
print(tide.rfromp("../dst/quick_sigfit.txt", thepts, numbins=10000))
print(tide.rfromp("../dst/quick_sigfit.txt", thepts, numbins=2000))
print(tide.rfromp("../dst/quick_sigfit.txt", thepts, numbins=500))
