#!/bin/csh -f

docker build . -t rapidtide

docker run -it rapidtide bash

docker run --volume=/Users/frederic:/data rapidtide \
    rapidtide2x
        /data/code/rapidtide/rapidtide/data/examples/src/fmri.nii.gz
        /data/code/rapidtide/rapidtide/data/examples/dst/dockertest
        -L

docker run --volume=/Users/frederic:/data rapidtide \
    happy \
        /data/code/rapidtide/rapidtide/data/examples/src/happyfmri.nii.gz \
        /data/code/rapidtide/rapidtide/data/examples/src/happyfmri.json \
        /data/code/rapidtide/rapidtide/data/examples/dst/happy_flip \
        --mklthreads=4 \
        --dodlfilter \
        --saveinfoasjson \
        --model=model_revised \
        --fliparteries

# allow network connections in Xquartz Security settings
xhost +
xhost +si:localuser:rapidtide

# Allow your local user access via xhost: xhost +SI:localuser:rapidtide and create a similar user with docker run option: --user=$(id -u):$(id -g)
docker run \
    --network host\
    --volume=/Users/frederic:/data \
    -it \
    -e DISPLAY=192.168.7.146:0 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -u rapidtide rapidtide \
    tidepool
