#!/usr/bin/env python

import numpy as np

import rapidtide.fit as tide_fit

ev1 = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0])
ev2 = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])
ev3 = np.array([0.0, 0.1, 0.4, 0.9, 1.6, 2.5])
thedata = np.array([0.2, 1.2, 2.2, 3.2, 4.2, 5.2])

evs = []
evs.append(ev1)
evs.append(ev2)
evs.append(ev3)

npevs = np.asarray(evs)
print(f"{evs=}")
print(f"{npevs=}")
print(f"{npevs.shape=}")


thefit, R2 = tide_fit.mlregress(evs, thedata, intercept=True)
print(f"{thefit=}")
print(f"{R2=}")

model = ev1 * thefit[0][0, 1] + ev2 * thefit[0][0, 2] + ev3 * thefit[0][0, 3] + thefit[0][0, 0]
for i in range(len(model)):
    print(thedata[i], model[i])
