#!/bin/csh -f

set rec1=$1
set rec2=$2
set dest=$3

foreach map ( lagmask lagtimes lagstrengths lagsigma mean MTT R2 refinemask corrout gaussout filtereddata fitNorm fitR fitR2 fitcoff p_lt_0p001_mask p_lt_0p005_mask p_lt_0p010_mask p_lt_0p050_mask )
    fslmaths $rec1'_'$map'.nii.gz' -sub $rec2'_'$map'.nii.gz' $dest'_'$map
    end
