#!/bin/bash

#installdir=`findinstalldir`
installdir=/tmp/src/rapidtide/rapidtide/data/examples/src/
pwd
ls
cd ${installdir}
wget  https://github.com/bbfrederick/rapidtide/raw/main/rapidtide/data/examples/testdatabundle.tgz -O - | tar -xz
pwd
ls
