#!/bin/bash

for LEVEL in min normal more max
do
    cd ~/code/rapidtide/rapidtide/data/examples/dst/${LEVEL}
    ls -1 > ~/code/rapidtide/rapidtide/data/examples/dst/${LEVEL}_filelist.txt
    for NDERIV in 0 1
    do
        RUN=${LEVEL}glm${NDERIV}
        cd ~/code/rapidtide/rapidtide/data/examples/dst/${RUN}
        ls -1 > ~/code/rapidtide/rapidtide/data/examples/dst/${RUN}_filelist.txt
    done
done

cd ~/code/rapidtide/rapidtide/data/examples/src
mkdir scratch

cp ../dst/min_filelist.txt scratch/base
sdiff ../dst/min_filelist.txt ../dst/normal_filelist.txt | grep ">" | awk '{print $2}' > scratch/newinnormal
sdiff ../dst/normal_filelist.txt ../dst/more_filelist.txt | grep ">" | awk '{print $2}' > scratch/newinmore
sdiff ../dst/more_filelist.txt ../dst/max_filelist.txt | grep ">" | awk '{print $2}' > scratch/newinmax

sdiff ../dst/min_filelist.txt ../dst/minglm0_filelist.txt | grep ">" | awk '{print $2}' > scratch/baseglm
sdiff ../dst/minglm0_filelist.txt ../dst/normalglm0_filelist.txt | grep ">" | awk '{print $2}' > scratch/newinnormalglm
sdiff scratch/newinnormal scratch/newinnormalglm | grep ">" | awk '{print $2}' > scratch/newinnormalglmonly
sdiff ../dst/normalglm0_filelist.txt ../dst/moreglm0_filelist.txt | grep ">" | awk '{print $2}' > scratch/newinmoreglm
sdiff scratch/newinmore scratch/newinmoreglm | grep ">" | awk '{print $2}' > scratch/newinmoreglmonly
sdiff ../dst/moreglm0_filelist.txt ../dst/maxglm0_filelist.txt | grep ">" | awk '{print $2}' > scratch/newinmaxglm
sdiff scratch/newinmax scratch/newinmaxglm | grep ">" | awk '{print $2}' > scratch/newinmaxglmonly
