#!/usr/bin/env python

import numpy as np
from rapidtide.util import makeslicetimes

numslices = 20
mbfac = 1
tr = 1.0

sliceorders = ["ascending", "descending",
                "ascending_interleaved", "descending_interleaved", 
                "ascending_interleaved_siemens", "descending_interleaved_siemens", 
                "ascending_interleaved_philips", "descending_interleaved_philips"]

for thesliceorder in sliceorders:
    thetimes = makeslicetimes(numslices, thesliceorder, tr=tr, multibandfac=mbfac)
    print('\n', thesliceorder)
    for i in range(len(thetimes)):
        print(i, '\t', thetimes[i])
