#!/bin/csh

spatialmi \
    ../../reference/HCP1200_lag_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    ../../reference/HCP1200_strength_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    --radius 2 \
    --spherical \
    ../dst/fastradius2_sphere

spatialmi \
    ../../reference/HCP1200_lag_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    ../../reference/HCP1200_strength_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    --radius 2 \
    --spherical \
    --sigma 1.5 \
    ../dst/fastradius2_1p5_sphere

spatialmi \
    ../../reference/HCP1200_lag_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    ../../reference/HCP1200_strength_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    --radius 3 \
    --spherical \
    ../dst/fastradius3_sphere

spatialmi \
    ../../reference/HCP1200_lag_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    ../../reference/HCP1200_strength_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    --radius 4 \
    --spherical \
    ../dst/fastradius4_sphere

spatialmi \
    ../../reference/HCP1200_lag_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    ../../reference/HCP1200_strength_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    --radius 5 \
    --spherical \
    ../dst/fastradius5_sphere
