#!/bin/csh

spatialmi \
    ../../reference/HCP1200_lag_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    ../../reference/HCP1200_strength_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    --radius 2 \
    ../dst/fastradius2

spatialmi \
    ../../reference/HCP1200_lag_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    ../../reference/HCP1200_strength_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    --radius 2 \
    --sigma 1.5 \
    ../dst/fastradius2_1p5

spatialmi \
    ../../reference/HCP1200_lag_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    ../../reference/HCP1200_strength_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    --radius 3 \
    ../dst/fastradius3

spatialmi \
    ../../reference/HCP1200_lag_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    ../../reference/HCP1200_strength_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    --radius 4 \
    ../dst/fastradius4

spatialmi \
    ../../reference/HCP1200_lag_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    ../../reference/HCP1200_strength_2mm.nii.gz \
    ../../reference/HCP1200_binmask_2mm.nii.gz	\
    --radius 5 \
    ../dst/fastradius5
