#!/bin/csh -f
rapidtide2x \
	fmri.nii.gz \
	../dst/dgsr \
        --limitoutput \
	--accheck \
        --despeckle \
        --despecklepasses=4 \
	--nofitfilt \
        --ampthresh=0.2854 \
        -F 0.005,0.08 \
	-r -15,15 \
	-f 2 -N 10000 --multiproc
