#!/bin/bash

tidepool \
    --uistyle big \
    --dataset \
    ../dst/sub-RAPIDTIDETEST_newpatch_ \
    ../dst/sub-RAPIDTIDETEST_newpatch0p9_ \
    ../dst/sub-RAPIDTIDETEST_newpatch0p2_ \
    ../dst/sub-RAPIDTIDETEST_newnopatch_
