#!/bin/bash

tidepool \
    --uistyle big \
    --dataset \
    ../dst/sub-RAPIDTIDETEST_ \
    ../dst/sub-RAPIDTIDETEST_preppass_ \
    ../dst/sub-RAPIDTIDETEST_sharpen_ \
    ../dst/sub-RAPIDTIDETEST_preppass_sharpen_
