#!/usr/bin/env python

import matplotlib.pyplot as plt

import rapidtide.filter as tide_filt

thelen = 300

thevals = tide_filt.mRect(thelen, phi=0.0)
plt.plot(thevals)
plt.plot(tide_filt.hamming(thelen))
plt.show()
