#!/usr/bin/env python

import rapidtide.io as tide_io
import numpy as np

newdata = np.random.rand(400)

samplerate = 25.0
starttime = -10.0

tide_io.writebidstsv("testbids", newdata, samplerate, columns=["initial"], starttime=starttime, append=False, debug=False)

samplerate, starttime, columns, data, compressed = tide_io.readbidstsv("testbids", debug=True)

print(samplerate, starttime, columns, data.shape, compressed)

scaled = 2.0 * data[0, :].reshape((-1))

print(scaled.shape)

tide_io.writebidstsv("testbids", scaled, samplerate, columns=["2x"], starttime=starttime, append=True, debug=False)
