#!/bin/bash

ccspatialdecomp \
    sub-RAPIDTIDETEST.nii.gz \
    ../dst/spatialdecomptest \
    --dmask sub-RAPIDTIDETEST_brainmask.nii.gz

temporaldecomp \
    sub-RAPIDTIDETEST.nii.gz \
    ../dst/temporaldecomptest \
    --dmask sub-RAPIDTIDETEST_brainmask.nii.gz 
