#!/bin/bash

rapidtide \
    --spatialfilt -1 \
    --nprocs -1 \
    --searchrange -5 20 \
    --simcalcrange 50 -1 \
    --outputlevel max \
    --refineglmderivs 2 \
    sub-RAPIDTIDETEST.nii.gz \
    ../dst/sub-RAPIDTIDETEST


retroglm \
    sub-RAPIDTIDETEST.nii.gz \
    ../dst/sub-RAPIDTIDETEST \
    --alternateoutput ../dst/retrotest \
    --nprocs -1 \
    --glmderivs 0 \
    --refineglmderivs 1 \
    --outputlevel max
