#!/bin/bash

MACHINE=$(uname -a | awk '{print $2}')
if [ ${MACHINE} == "mickey" ]; then
    echo "running on mickey"
    ROOT=/home/frederic/code/rapidtide/rapidtide
else
    echo "not running on mickey"
    ROOT=/Users/frederic/code/rapidtide/rapidtide
fi

cd ${ROOT}/experimental

for MODEL in model_cnn_pytorch*
do
    applydlfilter \
        ${ROOT}/data/examples/src/happy_desc-stdrescardfromfmri_timeseries.json:cardiacfromfmri_25.0Hz \
        ${ROOT}/data/examples/dst/${MODEL}_filtered \
        --model ${ROOT}/experimental/${MODEL} \
        --nodisplay
done
