#!/bin/csh -f

happyx \
    ses-060_bold_trunc.nii.gz \
    ses-060_bold_trunc.json \
    ../dst/XXX \
    --dodlfilter \
    --motionfile=ses-060_bold_trunc_prefiltered_func_data_mcf.par

#happyx \
    #sub-01_ses-059_task-rest_run-001_bold.nii.gz \
    #sub-01_ses-059_task-rest_run-001_bold.json \
    #../dst/happyx_motfilt_gauss \
    #--gridkernel='gauss' \
    #--gridbins=4.5 \
    #--numskip=10 \
    #--motionfile=sub-01_ses-059_task-rest_run-001_bold_prefiltered_func_data_mcf.par 
#
#happyx \
    #sub-01_ses-059_task-rest_run-001_bold.nii.gz \
    #sub-01_ses-059_task-rest_run-001_bold.json \
    #../dst/happyx_motfilt \
    #--numskip=10 \
    #--motionfile=sub-01_ses-059_task-rest_run-001_bold_prefiltered_func_data_mcf.par 
#
#happyx \
    #sub-01_ses-059_task-rest_run-001_bold.nii.gz \
    #sub-01_ses-059_task-rest_run-001_bold.json \
    #../dst/happyx \
    #--numskip=10 \
    #--cardcalconly
