#!/bin/bash

for STOP in 2 3 4 5 6 7 8
do
    filttc ../dst/happy_desc-stdrescardfromfmri_timeseries.json:cardiacfromfmri_25.0Hz \
    ../dst/stopfreq_${STOP} \
    --filterfreqs 0.0 1.0 \
    --filterstopfreqs 0.0 ${STOP}
done

showtc ../dst/stopfreq*.json --format separate
