#!/bin/bash

atlasaverage \
    ../../reference/HCP1200_lag_2mm.nii.gz \
    ../../reference/JHU-ArterialTerritories-LVL1_space-MNI152NLin6Asym_2mm.nii.gz \
    ../dst/atlastest \
    --headerline --debug

atlasaverage \
    ../../reference/HCP1200_lag_2mm.nii.gz \
    ../../reference/JHU-ArterialTerritories-LVL1_space-MNI152NLin6Asym_2mm.nii.gz \
    ../dst/atlastest_ignorezeros \
    --ignorezeros \
    --headerline --debug
