#!/bin/bash

rapidtide \
    --nprocs -1 \
    --passes 3 \
    --refinetype unweighted_average \
    --numnull 0 \
    --externalglm \
    --nolimitoutput \
    sub-RAPIDTIDETEST.nii.gz \
    ../dst/sub-RAPIDTIDETEST_newglm

rapidtide \
    --nprocs -1 \
    --passes 3 \
    --refinetype unweighted_average \
    --numnull 0 \
    --nolimitoutput \
    sub-RAPIDTIDETEST.nii.gz \
    ../dst/sub-RAPIDTIDETEST_oldglm

retroglm sub-RAPIDTIDETEST.nii.gz ../dst/sub-RAPIDTIDETEST_oldglm --alternateoutput ../dst/rehydrated --nprocs -1 --debug

for glm in old new
do
    for map in lfofilterR lfofilterR2 lfofilterMean lfofilterCoeff lfofilterNorm lfofilterInbandVarianceBefore lfofilterInbandVarianceAfter lfofilterInbandVarianceChange 
    do
        fslmaths \
            ../dst/rehydrated_desc-${map}_map.nii.gz \
            -sub \
            ../dst/sub-RAPIDTIDETEST_${glm}glm_desc-${map}_map.nii.gz \
            ../dst/diff_${glm}_${map}
        therange=`fslstats ../dst/diff_${glm}_${map} -R`
        echo ${glm} ${map}: ${therange}
    done

    for map in lfofilterRemoved_bold lfofilterCleaned_bold
    do
        fslmaths \
            ../dst/rehydrated_desc-${map}.nii.gz \
            -sub \
            ../dst/sub-RAPIDTIDETEST_${glm}glm_desc-${map}.nii.gz \
            ../dst/diff_${glm}_${map}
        therange=`fslstats ../dst/diff_${glm}_${map} -R`
        echo ${glm} ${map}: ${therange}
    done
done
