#!/bin/bash

rapidtide \
    --spatialfilt -1 \
    --nprocs -1 \
    --searchrange -5 20 \
    --simcalcrange 50 -1 \
    --outputlevel more \
    --dofinalrefine \
    --graymattermask sub-RAPIDTIDETEST_synthseg.nii.gz:SSEG_GRAY \
    --brainmask sub-RAPIDTIDETEST_brainmask.nii.gz \
    --whitemattermask sub-RAPIDTIDETEST_synthseg.nii.gz:SSEG_WHITE \
    --csfmask sub-RAPIDTIDETEST_synthseg.nii.gz:SSEG_CSF \
    sub-RAPIDTIDETEST.nii.gz \
    ../dst/sub-RAPIDTIDETEST

##retroregress sub-RAPIDTIDETEST.nii.gz ../dst/sub-RAPIDTIDETEST --alternateoutput ../dst/0deriv --nprocs -1 

retroregress \
    sub-RAPIDTIDETEST.nii.gz \
    ../dst/sub-RAPIDTIDETEST \
    --alternateoutput ../dst/specialtest \
    --nprocs -1 \
    --outputlevel normal

#retroregress sub-RAPIDTIDETEST.nii.gz ../dst/sub-RAPIDTIDETEST --alternateoutput ../dst/0deriv_refined --nprocs -1 --regressderivs 0 --makepseudofile --outputlevel max --refinedelay --nofilterwithrefineddelay
#retroregress sub-RAPIDTIDETEST.nii.gz ../dst/sub-RAPIDTIDETEST --alternateoutput ../dst/0deriv_refinedfit --nprocs -1 --regressderivs 0 --makepseudofile --outputlevel max --refinedelay
##retroregress sub-RAPIDTIDETEST.nii.gz ../dst/sub-RAPIDTIDETEST --alternateoutput ../dst/2deriv --nprocs -1 --regressderivs 2
##retroregress sub-RAPIDTIDETEST.nii.gz ../dst/sub-RAPIDTIDETEST --alternateoutput ../dst/3deriv --nprocs -1 --regressderivs 3

ALTNAME=1deriv

#for map in lfofilterR lfofilterR2 lfofilterMean lfofilterCoeff lfofilterCoeffDeriv1 lfofilterNorm lfofilterInbandVarianceBefore lfofilterInbandVarianceAfter lfofilterInbandVarianceChange 
#do
#    fslmaths \
#        ../dst/${ALTNAME}_desc-${map}_map.nii.gz \
#        -sub \
#        ../dst/sub-RAPIDTIDETEST_desc-${map}_map.nii.gz \
#        ../dst/diff_${map}
#    therange=`fslstats ../dst/diff_${map} -R`
#    echo ${map}: ${therange}
#done
#
##for map in processed_mask corrfit_mask maxtime_map
##do
##    readname=`echo ${map} | sed 's/_/READ_/g'`
##    fslmaths \
#        ../dst/${ALTNAME}_desc-${readname}.nii.gz \
#        -sub \
#        ../dst/sub-RAPIDTIDETEST_desc-${map}.nii.gz \
#        ../dst/diff_${map}
#    therange=`fslstats ../dst/diff_${map} -R`
#    echo ${map}: ${therange}
#done

#for map in datatofilter_bold
#do
    #fslmaths \
        #../dst/${ALTNAME}_desc-${map}.nii.gz \
        #-sub \
        #../dst/sub-RAPIDTIDETEST_desc-${map}.nii.gz \
        #../dst/diff_${map}
    #therange=`fslstats ../dst/diff_${map} -R`
    #echo ${map}: ${therange}
#done

#for map in lfofilterEV_bold lfofilterEVDeriv1_bold lfofilterRemoved_bold lfofilterCleaned_bold
#do
#    fslmaths \
#        ../dst/${ALTNAME}_desc-${map}.nii.gz \
#        -sub \
#        ../dst/sub-RAPIDTIDETEST_desc-${map}.nii.gz \
#        ../dst/diff_${map}
#    therange=`fslstats ../dst/diff_${map} -R`
#    echo ${map}: ${therange}
#done
#
