#!/bin/bash

#rapidtide \
    #--nprocs -1 \
    #--passes 3 \
    #--refinetype unweighted_average \
    #--numnull 0 \
    #--nolimitoutput \
    #--focaldebug \
    ##sub-RAPIDTIDETEST.nii.gz \
    #../dst/sub-RAPIDTIDETEST

#retroglm sub-RAPIDTIDETEST.nii.gz ../dst/sub-RAPIDTIDETEST --alternateoutput ../dst/rehydrated --nprocs -1 --debug

for map in lfofilterR lfofilterR2 lfofilterMean lfofilterCoeff lfofilterNorm lfofilterInbandVarianceBefore lfofilterInbandVarianceAfter lfofilterInbandVarianceChange 
do
    fslmaths \
        ../dst/rehydrated_desc-${map}_map.nii.gz \
        -sub \
        ../dst/sub-RAPIDTIDETEST_desc-${map}_map.nii.gz \
        ../dst/diff_${map}
    therange=`fslstats ../dst/diff_${map} -R`
    echo ${map}: ${therange}
done

for map in processed_mask maxtime_map
do
    readname=`echo ${map} | sed 's/_/READ_/g'`
    fslmaths \
        ../dst/rehydrated_desc-${readname}.nii.gz \
        -sub \
        ../dst/sub-RAPIDTIDETEST_desc-${map}.nii.gz \
        ../dst/diff_${map}
    therange=`fslstats ../dst/diff_${map} -R`
    echo ${map}: ${therange}
done

for map in datatofilter_bold lfofilterRemoved_bold lfofilterCleaned_bold
do
    fslmaths \
        ../dst/rehydrated_desc-${map}.nii.gz \
        -sub \
        ../dst/sub-RAPIDTIDETEST_desc-${map}.nii.gz \
        ../dst/diff_${map}
    therange=`fslstats ../dst/diff_${map} -R`
    echo ${map}: ${therange}
done

