#!/bin/csh -f

happyx \
    sub-01_ses-060_task-rest_run-001_bold.nii.gz \
    sub-01_ses-060_task-rest_run-001_bold.json \
    ../dst/happyx_motfilt_0p6 \
    --motionfile=sub-01_ses-060_task-rest_run-001_bold_prefiltered_func_data_mcf.par --envcutoff=0.6
