#!/bin/csh -f

showxcorrx \
    lt_HbO \
    rt_HbO \
    --samplerate 12.5 \
    --filterband lfo \
    --invert \
    --searchrange -15 15 \
    --similaritymetric correlation \
    --zeropad 0 --debug

showxcorrx \
    lt_HbO \
    rt_HbO \
    --samplerate 12.5 \
    --filterband lfo \
    --invert \
    --searchrange -15 15 \
    --similaritymetric correlation \
    --zeropad -1 --debug
