#!/bin/bash

atlasaverage \
    ../../reference/HCP1200v2_maxtime_2mm.nii.gz \
    ../../reference/JHU-ArterialTerritoriesNoVent-LVL1_space-MNI152NLin6Asym_2mm.nii.gz \
    ../dst/JHU-ArterialTerritoriesNoVent-LVL1-seg4_space-MNI152NLin6Asym_2mm \
    --ignorezeros \
    --numpercentiles 3 \
    --includemask /opt/fsl-latest/data/standard/MNI152_T1_2mm_brain_mask.nii.gz \
    --extramask /opt/fsl-latest/data/standard/MNI152_T1_2mm_brain_mask.nii.gz \
    --summarymethod median \
    --headerline

atlasaverage \
    HCP1200v2_maxtime_1mm.nii.gz \
    ../../reference/JHU-ArterialTerritoriesNoVent-LVL1_space-MNI152NLin6Asym_1mm.nii.gz \
    ../dst/JHU-ArterialTerritoriesNoVent-LVL1-seg4_space-MNI152NLin6Asym_1mm \
    --ignorezeros \
    --numpercentiles 3 \
    --includemask /opt/fsl-latest/data/standard/MNI152_T1_1mm_brain_mask.nii.gz \
    --extramask /opt/fsl-latest/data/standard/MNI152_T1_1mm_brain_mask.nii.gz \
    --summarymethod median \
    --headerline

atlasaverage \
    sub-RAPIDTIDETEST.nii.gz \
    sub-RAPIDTIDETEST_dseg.nii.gz \
    ../dst/synthsegaverages \
    --ignorezeros \
    --numpercentiles 3 \
    --includemask sub-RAPIDTIDETEST_brainmask.nii.gz \
    --regionlabelfile dseglabels.txt \
    --summarymethod mean 

atlasaverage \
    sub-RAPIDTIDETEST.nii.gz \
    sub-RAPIDTIDETEST_dseg.nii.gz \
    ../dst/synthsegaverages_pctnorm \
    --normmethod pct \
    --ignorezeros \
    --numpercentiles 3 \
    --includemask sub-RAPIDTIDETEST_brainmask.nii.gz \
    --regionlabelfile dseglabels.txt \
    --summarymethod mean 

