#!/bin/csh -f

#happy \
#    sub-HAPPYTEST.nii.gz \
#    sub-HAPPYTEST.json \
#    ../dst/happy_vanilla \
#    --nprocs 1

#happy \
#    sub-HAPPYTEST.nii.gz \
#    sub-HAPPYTEST.json \
#    --mpphaseproject \
#    ../dst/happy_mpphaseproj \
#    --nprocs -1

#happy \
#    sub-HAPPYTEST.nii.gz \
#    sub-HAPPYTEST.json \
#    --mpdetrend \
#    ../dst/happy_mpdetrend \
#    --nprocs -1

#happy \
#    sub-HAPPYTEST.nii.gz \
#    sub-HAPPYTEST.json \
#    --mpphaseproject \
#    --mpdetrend \
#    ../dst/happy_mpdetrend_mpphaseproj \
#    --nprocs -1

#happy \
#    sub-HAPPYTEST.nii.gz \
#    sub-HAPPYTEST.json \
#    --prefillcongrid \
#    ../dst/happy_vanilla_prefill \
#    --nprocs 1

#happy \
#    sub-HAPPYTEST.nii.gz \
#    sub-HAPPYTEST.json \
#    --prefillcongrid \
#    --mpphaseproject \
#    ../dst/happy_mpphaseproj_prefill \
#    --nprocs -1

#happy \
#    sub-HAPPYTEST.nii.gz \
#    sub-HAPPYTEST.json \
#    --prefillcongrid \
#    --mpdetrend \
#    ../dst/happy_mpdetrend_prefill \
#    --nprocs -1

#happy \
#    sub-HAPPYTEST.nii.gz \
#    sub-HAPPYTEST.json \
#    --prefillcongrid \
#    --mpphaseproject \
#    --mpdetrend \
#    ../dst/happy_mpdetrend_mpphaseproj_prefill \
#    --nprocs -1

#happy \
    #sub-HAPPYTEST.nii.gz \
    #sub-HAPPYTEST.json \
    #--mpphaseproject \
    #--mpdetrend \
    #--nocongridcache \
    #../dst/happy_mpdetrend_mpphaseproj_nocache \
    #--nprocs -1

#happy \
    #sub-HAPPYTEST.nii.gz \
    #sub-HAPPYTEST.json \
    #../dst/happy_mask \
    #--processmask sub-HAPPYTEST_mask.nii.gz \
    #--nprocs -1

#    --motionfile sub-HAPPYTEST_mcf.par \

#happy \
    #sub-HAPPYTEST.nii.gz \
    #sub-HAPPYTEST.json \
    #../dst/happy \
    #--increaseoutputlevel \
    #--model model_cnn_pytorch \
    #--usepytorch \
    #--nprocs -1

happy \
    sub-HAPPYTEST.nii.gz \
    sub-HAPPYTEST.json \
    ../dst/happy_pytorch \
    --model /Users/frederic/code/rapidtide/rapidtide/experimental/model_cnn_pytorch_w064_l19_fn50_fl05_e025_t4.0_ct0.72_s20_d1_relu_normaligned \
    --increaseoutputlevel \
    --usenewvesselmethod \
    --nprocs -1

happy \
    sub-HAPPYTEST.nii.gz \
    sub-HAPPYTEST.json \
    ../dst/happy_pytorchbp \
    --model /Users/frederic/code/rapidtide/rapidtide/experimental/model_cnn_pytorch_w064_l19_fn50_fl05_e025_t4.0_ct0.72_s20_d1_relu_usebadpts_normaligned \
    --increaseoutputlevel \
    --usenewvesselmethod \
    --nprocs -1

#happy \
#    sub-HAPPYTEST.nii.gz \
#    sub-HAPPYTEST.json \
#    ../dst/happy_tensorflow \
#    --increaseoutputlevel \
#    --usenewvesselmethod \
#    --usetensorflow \
#    --nprocs -1
