#!/bin/bash

showstxcorr \
    lt_HbO \
    rt_HbO \
    ../dst/hoot \
    --samplerate 12.5 \
    --filterband lfo \
    --windowwidth 60.0 \
    --stepsize 5.0 \
    --invert \
    --corrthresh 0.6 \
    --searchrange -15 15 \
    --detrendorder 1
