#!/bin/bash

#rapidtide \
	#--spatialfilt 2 \
        #--nprocs -1 \
        #--passes 3 \
        #--similaritymetric hybrid \
        #--norefinedespeckled \
        #--filterband lfo \
        #sub-RAPIDTIDETEST.nii.gz \
        #../dst/sub-RAPIDTIDETEST_full

for STARTTR in 000 010 020 030 040 050 060 070 080 090 100 110 120 130 140 150 160 170 180 190 200 210 220 230
do
    ENDTR=`echo ${STARTTR} | awk '{print $1+30}'`
    REGRESSORSTARTTIME=`echo ${STARTTR} | awk '{print $1*1.5}'`
    rapidtide \
	--spatialfilt 2 \
        --nprocs -1 \
        --nofitfilt \
        --peakfittype quad \
        --regressor ../dst/sub-RAPIDTIDETEST_full_desc-movingregressor_timeseries.json:pass3 \
        --regressorstart ${REGRESSORSTARTTIME} \
        --similaritymetric correlation \
        --filterband lfo \
        --passes 1 \
        --despecklepasses 4 \
        --searchrange -20 20 \
        --noglm \
        --timerange ${STARTTR} ${ENDTR} \
        --norefineoffset \
        sub-RAPIDTIDETEST.nii.gz \
        ../dst/correlation_45s_start_${STARTTR}
done

