#!/usr/bin/env python

import sys

import numpy as np
from numpy.polynomial import Polynomial

fname = "testdata.txt"
theinputdata = np.loadtxt(fname, dtype="float")

xvals = theinputdata[:, 0]
yvals = theinputdata[:, 1]

thecoffs = Polynomial.fit(xvals, yvals, 1).convert().coef[::-1]
fitslope = thecoffs[0]
fitintercept = thecoffs[1]

print(f"{fitslope=}, {fitintercept=}")

for i in range(len(xvals)):
    print(xvals[i], yvals[i], xvals[i] * fitslope + fitintercept)
