#!/bin/bash

#rapidtide \
#    --spatialfilt 3 \
#    --nprocs -1 \
#    --searchrange -7.5 30 \
#    --simcalcrange 50 -1 \
#    --graymattermask sub-RAPIDTIDETEST_synthseg.nii.gz:SSEG_GRAY \
#    --whitemattermask sub-RAPIDTIDETEST_synthseg.nii.gz:SSEG_WHITE \
#    --csfmask sub-RAPIDTIDETEST_synthseg.nii.gz:SSEG_CSF \
#    --nofitfilt \
#    --outputlevel max \
#    --showtimings \
#    sub-RAPIDTIDETEST.nii.gz \
#    ../dst/sub-RAPIDTIDETEST_nobrain

#rapidtide \
#    --spatialfilt 3 \
#    --nprocs -1 \
#    --searchrange -7.5 30 \
#    --simcalcrange 50 -1 \
#    --brainmask sub-RAPIDTIDETEST_brainmask.nii.gz \
#    --nofitfilt \
#    --outputlevel max \
#    --showtimings \
#    sub-RAPIDTIDETEST.nii.gz \
#    ../dst/sub-RAPIDTIDETEST_brainonly

#rapidtide \
    #--spatialfilt 3 \
    #--nprocs -1 \
    #--searchrange -7.5 30 \
    #--simcalcrange 50 -1 \
    #--graymattermask sub-RAPIDTIDETEST_synthseg.nii.gz:SSEG_GRAY \
    #--brainmask sub-RAPIDTIDETEST_brainmask.nii.gz \
    #--whitemattermask sub-RAPIDTIDETEST_synthseg.nii.gz:SSEG_WHITE \
    #--csfmask sub-RAPIDTIDETEST_synthseg.nii.gz:SSEG_CSF \
    #--nofitfilt \
    #--outputlevel max \
    #--showtimings \
    #sub-RAPIDTIDETEST.nii.gz \
    #../dst/sub-RAPIDTIDETEST
 
rapidtide \
    sub-RAPIDTIDETEST.nii.gz \
    ../dst/sub-RAPIDTIDETEST \
    --searchrange -5 20 \
    --spatialfilt 4 \
    --nprocs -1 \
    --outputlevel max \
    --robustdelayfit
