#!/usr/bin/env python

import numpy as np
import rapidtide.regionops as tide_regionops
import rapidtide.io as tide_io

infile, infile_data, infile_hdr, infiledims, infilesizes = tide_io.readfromnifti("/opt/fsl-latest/data/standard/MNI152_T1_2mm_brain_mask.nii.gz")

labels = tide_regionops.partition_3d(
    infile_data.astype(np.uint16),
    n_regions=64,
    connectivity=6,
    seed=42,
    balance_alpha=0.5,  # encourages similar volumes
    jitter=0.1          # reduces grid artifacts
)

tide_io.savetonifti(labels, infile_hdr, "../dst/MNIrandom_12")
