#!/bin/csh -f

happy_trans \
    happyfmri.nii.gz \
    happyfmri.json \
    ../dst/happy_noflip \
    --mklthreads 8 \
    --dodlfilter \
    --model model_revised \
    --aliasedcorrelation \
    --spatialglm \
    --temporalglm

#happy \
#    happyfmri.nii.gz \
#    happyfmri.json \
#    ../dst/happy_noflip \
#    --mklthreads=8 \
#    --dodlfilter \
#    --saveinfoasjson \
#    --model=model_revised \
#    --aliasedcorrelation \
#    --spatialglm --temporalglm
#
#happy \
#    happyfmri.nii.gz \
#    happyfmri.json \
#    ../dst/happy_flip \
#    --mklthreads=8 \
#    --dodlfilter \
#    --saveinfoasjson \
#    --model=model_revised \
#    --fliparteries \
#    --aliasedcorrelation \
#    --glm
