#!/usr/bin/env bash

source activate tensorflowgpu

/cm/shared/anaconda3/bin/applydlfilter \
    /home/frederic/code/rapidtide/rapidtide/experimental/cardfiles \
    /home/frederic/code/rapidtide/rapidtide/experimental/predfiles \
    --model=/home/frederic/code/rapidtide/rapidtide/experimental/model_cnn_w128_l10_fn10_fl5_e20_t4.0_relu_normaligned \
    --filesarelists \
    --nodisplay
