#!/bin/bash

#SBATCH	--cpus-per-task=1
#SBATCH	--gres=gpu:1
#SBATCH	--mem=8G

cd /home/frederic/code/rapidtide/rapidtide/experimental
/home/frederic/.conda/envs/testmic/bin/python /home/frederic/code/rapidtide/rapidtide/experimental/batchtrain

