#!/usr/bin/env python
# -*- coding: latin-1 -*-
#
#   Copyright 2016-2021 Blaise Frederick
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#
from __future__ import print_function, division

import sys
import os
import subprocess


def main():
    # get the command line parameters
    execdir = sys.path[0]
    validcommands = [
        "aligntcs",
        "applydlfilter",
        "atlasaverage",
        "atlastool",
        "ccorrica",
        "endtidalproc",
        "filtnifti",
        "filttc",
        "fingerprint",
        "glmfilt",
        "happy",
        "happy2std",
        "happy_legacy",
        "happywarp",
        "harmonogram",
        "histnifti",
        "histtc",
        "physiofreq",
        "pixelcomp",
        "plethquality",
        "polyfitim",
        "rapidtide",
        "rapidtide2std",
        "rapidtide2x_legacy",
        "rapidtide_dispatcher",
        "resamp1tc",
        "resamplenifti",
        "showarbcorr",
        "showhist",
        "showstxcorr",
        "showtc",
        "showxcorr_legacy",
        "showxcorrx",
        "showxy",
        "simdata",
        "spatialdecomp",
        "spatialfit",
        "spectrogram",
        "synthASL",
        "tcfrom3col",
        "temporaldecomp",
        "testhrv",
        "threeD",
        "tidepool",
        "xyzzy",
    ]

    thecommand = sys.argv[1:]
    if thecommand[0] in validcommands:
        # the script exists, now check if it is installed
        if os.path.isfile(os.path.join(execdir, thecommand[0])):
            subprocess.call(thecommand)
        elif thecommand[0] == "xyzzy":
            subprocess.call("/bin/bash")
        else:
            print(thecommand[0], "is a rapidtide script, but is not installed")
    else:
        print(thecommand[0], "is not a script in the rapidtide package")


if __name__ == "__main__":
    main()
