#!/usr/bin/env python
# -*- coding: latin-1 -*-
#
#   Copyright 2016-2019 Blaise Frederick
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#
#       $Author: frederic $
#       $Date: 2016/07/11 14:50:43 $
#       $Id: showhist,v 1.5 2016/07/11 14:50:43 frederic Exp $
#
from __future__ import print_function

import rapidtide.io as tide_io
from matplotlib.pyplot import plot, xlabel, ylabel, title, legend, show, savefig, bar
import argparse


def _getparser():
    # get the command line parameters
    parser = argparse.ArgumentParser(prog='showxy',
                                     description='Plots xy histogram data in text file.',
                                     usage='%(prog)s texfilename [options]')
    parser.add_argument('infilename',
                        help='a text file containing histogram data')
    parser.add_argument('--xlabel',
                        dest='thexlabel',
                        type=str,
                        metavar='XLABEL',
                        help='use XLABEL on the x axis',
                        default=None)
    parser.add_argument('--ylabel',
                        dest='theylabel',
                        type=str,
                        metavar='YLABEL',
                        help='use YLABEL on the x axis',
                        default=None)
    parser.add_argument('--title',
                        dest='thetitle',
                        type=str,
                        metavar='TITLE',
                        help='use TITLE at the top of the graph',
                        default=None)
    parser.add_argument('--outputfile',
                        dest='outputfile',
                        type=str,
                        metavar='FILENAME',
                        help='save plot to FILENAME rather then displaying on the screen',
                        default=None)
    parser.add_argument('--dobars',
                        dest='dobars',
                        action='store_true',
                        help='plot bars rather than lines',
                        default=False)
    parser.add_argument('--debug',
                        dest='debug',
                        action='store_true',
                        help='plot bars rather than lines',
                        default=False)

    args = parser.parse_args()

    if args.debug:
        print(args)

    return parser


def main():
    # get the command line parameters
    theparser = _getparser()
    args = theparser.parse_args()

    indata = tide_io.readvecs(args.infilename)
    xvecs = indata[0, :]
    yvecs = indata[1, :]
    if args.dobars:
        bar(xvecs, yvecs, width=(0.8 * (xvecs[1] - xvecs[0])), color='g')
    else:
        plot(xvecs, yvecs, 'r')

    if args.thetitle is not None:
        title(args.thetitle)

    if args.thexlabel is not None:
        xlabel(args.thexlabel, fontsize=16, fontweight='bold')

    if args.theylabel is not None:
        ylabel(args.theylabel, fontsize=16, fontweight='bold')

    if args.outputfile is None:
        show()
    else:
        savefig(args.outputfile, bbox_inches='tight')

if __name__ == '__main__':
    main()

