#!/usr/bin/env python
# -*- coding: latin-1 -*-
#
#   Copyright 2016-2019 Blaise Frederick
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#
# $Author: frederic $
#       $Date: 2016/07/11 14:50:43 $
#       $Id: showxcorr,v 1.41 2016/07/11 14:50:43 frederic Exp $
#
from __future__ import print_function, division

import bisect
import numpy as np
from matplotlib.pyplot import figure, plot, show
import rapidtide.io as tide_io
import rapidtide.util as tide_util
import argparse


# get the command line parameters
parser = argparse.ArgumentParser(description='Plots the data in text files.')
parser.add_argument('infilename',
                    help='the name of the input three column file')
parser.add_argument('timestep',
                    type=float,
                    help='the time step of the output time course in seconds')
parser.add_argument('numpoints',
                    type=int,
                    help='the number of output time points')
parser.add_argument('outfilename',
                    help='the name of the output time course file')
parser.add_argument('--debug',
                    action='store_true',
                    help='turn on additional debugging output')
args = parser.parse_args()

if args.debug:
    print(args)

# now make the vector
inputdata = tide_io.readvecs(args.infilename)
timeaxis = np.arange(0.0, args.numpoints * args.timestep, args.timestep)
outputdata = 0.0 * timeaxis
outputdata = tide_util.maketcfrom3col(inputdata, timeaxis, outputdata, debug=args.debug)
tide_io.writenpvecs(outputdata, args.outfilename)
