# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tidepoolTemplate.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1118, 711)
        MainWindow.setMinimumSize(QtCore.QSize(256, 256))
        MainWindow.setMaximumSize(QtCore.QSize(1118, 16777215))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.histogram_groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.histogram_groupBox_2.setGeometry(QtCore.QRect(440, 505, 671, 161))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogram_groupBox_2.sizePolicy().hasHeightForWidth())
        self.histogram_groupBox_2.setSizePolicy(sizePolicy)
        self.histogram_groupBox_2.setMinimumSize(QtCore.QSize(100, 100))
        self.histogram_groupBox_2.setMaximumSize(QtCore.QSize(700, 283))
        self.histogram_groupBox_2.setObjectName(_fromUtf8("histogram_groupBox_2"))
        self.logOutput = QtGui.QTextEdit(self.histogram_groupBox_2)
        self.logOutput.setGeometry(QtCore.QRect(10, 30, 651, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.logOutput.setFont(font)
        self.logOutput.setObjectName(_fromUtf8("logOutput"))
        self.imageData_groupBox = QtGui.QGroupBox(self.centralwidget)
        self.imageData_groupBox.setGeometry(QtCore.QRect(10, 0, 1100, 296))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageData_groupBox.sizePolicy().hasHeightForWidth())
        self.imageData_groupBox.setSizePolicy(sizePolicy)
        self.imageData_groupBox.setMinimumSize(QtCore.QSize(1100, 100))
        self.imageData_groupBox.setMaximumSize(QtCore.QSize(1100, 296))
        self.imageData_groupBox.setObjectName(_fromUtf8("imageData_groupBox"))
        self.label = QtGui.QLabel(self.imageData_groupBox)
        self.label.setGeometry(QtCore.QRect(10, 520, 521, 16))
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.layoutWidget = QtGui.QWidget(self.imageData_groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 1091, 271))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.largeimage_horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.largeimage_horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.largeimage_horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.largeimage_horizontalLayout.setObjectName(_fromUtf8("largeimage_horizontalLayout"))
        self.main_graphicsView = GraphicsLayoutWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_graphicsView.sizePolicy().hasHeightForWidth())
        self.main_graphicsView.setSizePolicy(sizePolicy)
        self.main_graphicsView.setMinimumSize(QtCore.QSize(778, 256))
        self.main_graphicsView.setMaximumSize(QtCore.QSize(778, 256))
        self.main_graphicsView.setSizeIncrement(QtCore.QSize(1, 1))
        self.main_graphicsView.setFrameShape(QtGui.QFrame.NoFrame)
        self.main_graphicsView.setAlignment(QtCore.Qt.AlignCenter)
        self.main_graphicsView.setObjectName(_fromUtf8("main_graphicsView"))
        self.largeimage_horizontalLayout.addWidget(self.main_graphicsView)
        self.graphicsView_colorbar = GraphicsView(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_colorbar.sizePolicy().hasHeightForWidth())
        self.graphicsView_colorbar.setSizePolicy(sizePolicy)
        self.graphicsView_colorbar.setMinimumSize(QtCore.QSize(30, 128))
        self.graphicsView_colorbar.setMaximumSize(QtCore.QSize(25, 256))
        self.graphicsView_colorbar.setSizeIncrement(QtCore.QSize(1, 1))
        self.graphicsView_colorbar.setObjectName(_fromUtf8("graphicsView_colorbar"))
        self.largeimage_horizontalLayout.addWidget(self.graphicsView_colorbar)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.dispmax_doubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.dispmax_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dispmax_doubleSpinBox.setDecimals(3)
        self.dispmax_doubleSpinBox.setObjectName(_fromUtf8("dispmax_doubleSpinBox"))
        self.verticalLayout_3.addWidget(self.dispmax_doubleSpinBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.resetDispLimits_Button = QtGui.QPushButton(self.layoutWidget)
        self.resetDispLimits_Button.setObjectName(_fromUtf8("resetDispLimits_Button"))
        self.verticalLayout_3.addWidget(self.resetDispLimits_Button)
        self.resetDispSmart_Button = QtGui.QPushButton(self.layoutWidget)
        self.resetDispSmart_Button.setObjectName(_fromUtf8("resetDispSmart_Button"))
        self.verticalLayout_3.addWidget(self.resetDispSmart_Button)
        self.saveDisp_Button = QtGui.QPushButton(self.layoutWidget)
        self.saveDisp_Button.setObjectName(_fromUtf8("saveDisp_Button"))
        self.verticalLayout_3.addWidget(self.saveDisp_Button)
        self.setMask_Button = QtGui.QPushButton(self.layoutWidget)
        self.setMask_Button.setObjectName(_fromUtf8("setMask_Button"))
        self.verticalLayout_3.addWidget(self.setMask_Button)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.dispmin_doubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.dispmin_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dispmin_doubleSpinBox.setDecimals(3)
        self.dispmin_doubleSpinBox.setObjectName(_fromUtf8("dispmin_doubleSpinBox"))
        self.verticalLayout_3.addWidget(self.dispmin_doubleSpinBox)
        self.largeimage_horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.gray_radioButton = QtGui.QRadioButton(self.layoutWidget)
        self.gray_radioButton.setObjectName(_fromUtf8("gray_radioButton"))
        self.verticalLayout_2.addWidget(self.gray_radioButton)
        self.thermal_radioButton = QtGui.QRadioButton(self.layoutWidget)
        self.thermal_radioButton.setObjectName(_fromUtf8("thermal_radioButton"))
        self.verticalLayout_2.addWidget(self.thermal_radioButton)
        self.GYR_radioButton = QtGui.QRadioButton(self.layoutWidget)
        self.GYR_radioButton.setObjectName(_fromUtf8("GYR_radioButton"))
        self.verticalLayout_2.addWidget(self.GYR_radioButton)
        self.rainbow_radioButton = QtGui.QRadioButton(self.layoutWidget)
        self.rainbow_radioButton.setObjectName(_fromUtf8("rainbow_radioButton"))
        self.verticalLayout_2.addWidget(self.rainbow_radioButton)
        self.viridis_radioButton = QtGui.QRadioButton(self.layoutWidget)
        self.viridis_radioButton.setObjectName(_fromUtf8("viridis_radioButton"))
        self.verticalLayout_2.addWidget(self.viridis_radioButton)
        self.jet_radioButton = QtGui.QRadioButton(self.layoutWidget)
        self.jet_radioButton.setObjectName(_fromUtf8("jet_radioButton"))
        self.verticalLayout_2.addWidget(self.jet_radioButton)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.aspects_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.aspects_checkBox.setObjectName(_fromUtf8("aspects_checkBox"))
        self.verticalLayout_5.addWidget(self.aspects_checkBox)
        self.report_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.report_pushButton.setObjectName(_fromUtf8("report_pushButton"))
        self.verticalLayout_5.addWidget(self.report_pushButton)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.largeimage_horizontalLayout.addLayout(self.verticalLayout_2)
        self.overlays_groupBox = QtGui.QGroupBox(self.centralwidget)
        self.overlays_groupBox.setGeometry(QtCore.QRect(10, 300, 421, 366))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overlays_groupBox.sizePolicy().hasHeightForWidth())
        self.overlays_groupBox.setSizePolicy(sizePolicy)
        self.overlays_groupBox.setMinimumSize(QtCore.QSize(230, 0))
        self.overlays_groupBox.setMaximumSize(QtCore.QSize(16777215, 683))
        self.overlays_groupBox.setObjectName(_fromUtf8("overlays_groupBox"))
        self.overlay_radioButton_05 = QtGui.QRadioButton(self.overlays_groupBox)
        self.overlay_radioButton_05.setGeometry(QtCore.QRect(10, 260, 151, 20))
        self.overlay_radioButton_05.setObjectName(_fromUtf8("overlay_radioButton_05"))
        self.overlay_graphicsView_01 = GraphicsLayoutWidget(self.overlays_groupBox)
        self.overlay_graphicsView_01.setGeometry(QtCore.QRect(10, 30, 198, 64))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overlay_graphicsView_01.sizePolicy().hasHeightForWidth())
        self.overlay_graphicsView_01.setSizePolicy(sizePolicy)
        self.overlay_graphicsView_01.setMinimumSize(QtCore.QSize(198, 64))
        self.overlay_graphicsView_01.setMaximumSize(QtCore.QSize(198, 64))
        self.overlay_graphicsView_01.setFrameShape(QtGui.QFrame.NoFrame)
        self.overlay_graphicsView_01.setAlignment(QtCore.Qt.AlignCenter)
        self.overlay_graphicsView_01.setObjectName(_fromUtf8("overlay_graphicsView_01"))
        self.overlay_radioButton_01 = QtGui.QRadioButton(self.overlays_groupBox)
        self.overlay_radioButton_01.setGeometry(QtCore.QRect(10, 90, 151, 20))
        self.overlay_radioButton_01.setObjectName(_fromUtf8("overlay_radioButton_01"))
        self.overlay_radioButton_02 = QtGui.QRadioButton(self.overlays_groupBox)
        self.overlay_radioButton_02.setGeometry(QtCore.QRect(220, 90, 151, 20))
        self.overlay_radioButton_02.setObjectName(_fromUtf8("overlay_radioButton_02"))
        self.overlay_radioButton_03 = QtGui.QRadioButton(self.overlays_groupBox)
        self.overlay_radioButton_03.setGeometry(QtCore.QRect(220, 175, 151, 20))
        self.overlay_radioButton_03.setObjectName(_fromUtf8("overlay_radioButton_03"))
        self.overlay_radioButton_04 = QtGui.QRadioButton(self.overlays_groupBox)
        self.overlay_radioButton_04.setGeometry(QtCore.QRect(10, 175, 151, 20))
        self.overlay_radioButton_04.setObjectName(_fromUtf8("overlay_radioButton_04"))
        self.corrout_radioButton = QtGui.QRadioButton(self.overlays_groupBox)
        self.corrout_radioButton.setGeometry(QtCore.QRect(10, 490, 151, 20))
        self.corrout_radioButton.setChecked(True)
        self.corrout_radioButton.setObjectName(_fromUtf8("corrout_radioButton"))
        self.overlay_radioButton_06 = QtGui.QRadioButton(self.overlays_groupBox)
        self.overlay_radioButton_06.setGeometry(QtCore.QRect(220, 260, 151, 20))
        self.overlay_radioButton_06.setObjectName(_fromUtf8("overlay_radioButton_06"))
        self.overlay_radioButton_07 = QtGui.QRadioButton(self.overlays_groupBox)
        self.overlay_radioButton_07.setGeometry(QtCore.QRect(10, 345, 151, 20))
        self.overlay_radioButton_07.setObjectName(_fromUtf8("overlay_radioButton_07"))
        self.overlay_radioButton_08 = QtGui.QRadioButton(self.overlays_groupBox)
        self.overlay_radioButton_08.setGeometry(QtCore.QRect(220, 345, 151, 20))
        self.overlay_radioButton_08.setObjectName(_fromUtf8("overlay_radioButton_08"))
        self.overlay_graphicsView_04 = GraphicsLayoutWidget(self.overlays_groupBox)
        self.overlay_graphicsView_04.setGeometry(QtCore.QRect(10, 115, 192, 64))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overlay_graphicsView_04.sizePolicy().hasHeightForWidth())
        self.overlay_graphicsView_04.setSizePolicy(sizePolicy)
        self.overlay_graphicsView_04.setMinimumSize(QtCore.QSize(192, 64))
        self.overlay_graphicsView_04.setMaximumSize(QtCore.QSize(192, 64))
        self.overlay_graphicsView_04.setFrameShape(QtGui.QFrame.NoFrame)
        self.overlay_graphicsView_04.setAlignment(QtCore.Qt.AlignCenter)
        self.overlay_graphicsView_04.setObjectName(_fromUtf8("overlay_graphicsView_04"))
        self.overlay_graphicsView_06 = GraphicsLayoutWidget(self.overlays_groupBox)
        self.overlay_graphicsView_06.setGeometry(QtCore.QRect(220, 200, 192, 64))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overlay_graphicsView_06.sizePolicy().hasHeightForWidth())
        self.overlay_graphicsView_06.setSizePolicy(sizePolicy)
        self.overlay_graphicsView_06.setMinimumSize(QtCore.QSize(192, 64))
        self.overlay_graphicsView_06.setMaximumSize(QtCore.QSize(192, 64))
        self.overlay_graphicsView_06.setFrameShape(QtGui.QFrame.NoFrame)
        self.overlay_graphicsView_06.setAlignment(QtCore.Qt.AlignCenter)
        self.overlay_graphicsView_06.setObjectName(_fromUtf8("overlay_graphicsView_06"))
        self.overlay_graphicsView_03 = GraphicsLayoutWidget(self.overlays_groupBox)
        self.overlay_graphicsView_03.setGeometry(QtCore.QRect(220, 115, 192, 64))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overlay_graphicsView_03.sizePolicy().hasHeightForWidth())
        self.overlay_graphicsView_03.setSizePolicy(sizePolicy)
        self.overlay_graphicsView_03.setMinimumSize(QtCore.QSize(192, 64))
        self.overlay_graphicsView_03.setMaximumSize(QtCore.QSize(192, 64))
        self.overlay_graphicsView_03.setFrameShape(QtGui.QFrame.NoFrame)
        self.overlay_graphicsView_03.setAlignment(QtCore.Qt.AlignCenter)
        self.overlay_graphicsView_03.setObjectName(_fromUtf8("overlay_graphicsView_03"))
        self.overlay_graphicsView_08 = GraphicsLayoutWidget(self.overlays_groupBox)
        self.overlay_graphicsView_08.setGeometry(QtCore.QRect(220, 285, 192, 64))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overlay_graphicsView_08.sizePolicy().hasHeightForWidth())
        self.overlay_graphicsView_08.setSizePolicy(sizePolicy)
        self.overlay_graphicsView_08.setMinimumSize(QtCore.QSize(192, 64))
        self.overlay_graphicsView_08.setMaximumSize(QtCore.QSize(192, 64))
        self.overlay_graphicsView_08.setFrameShape(QtGui.QFrame.NoFrame)
        self.overlay_graphicsView_08.setAlignment(QtCore.Qt.AlignCenter)
        self.overlay_graphicsView_08.setObjectName(_fromUtf8("overlay_graphicsView_08"))
        self.overlay_graphicsView_05 = GraphicsLayoutWidget(self.overlays_groupBox)
        self.overlay_graphicsView_05.setGeometry(QtCore.QRect(10, 200, 192, 64))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overlay_graphicsView_05.sizePolicy().hasHeightForWidth())
        self.overlay_graphicsView_05.setSizePolicy(sizePolicy)
        self.overlay_graphicsView_05.setMinimumSize(QtCore.QSize(192, 64))
        self.overlay_graphicsView_05.setMaximumSize(QtCore.QSize(192, 64))
        self.overlay_graphicsView_05.setFrameShape(QtGui.QFrame.NoFrame)
        self.overlay_graphicsView_05.setAlignment(QtCore.Qt.AlignCenter)
        self.overlay_graphicsView_05.setObjectName(_fromUtf8("overlay_graphicsView_05"))
        self.overlay_graphicsView_02 = GraphicsLayoutWidget(self.overlays_groupBox)
        self.overlay_graphicsView_02.setGeometry(QtCore.QRect(220, 30, 192, 64))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overlay_graphicsView_02.sizePolicy().hasHeightForWidth())
        self.overlay_graphicsView_02.setSizePolicy(sizePolicy)
        self.overlay_graphicsView_02.setMinimumSize(QtCore.QSize(192, 64))
        self.overlay_graphicsView_02.setMaximumSize(QtCore.QSize(192, 64))
        self.overlay_graphicsView_02.setFrameShape(QtGui.QFrame.NoFrame)
        self.overlay_graphicsView_02.setAlignment(QtCore.Qt.AlignCenter)
        self.overlay_graphicsView_02.setObjectName(_fromUtf8("overlay_graphicsView_02"))
        self.overlay_graphicsView_07 = GraphicsLayoutWidget(self.overlays_groupBox)
        self.overlay_graphicsView_07.setGeometry(QtCore.QRect(10, 285, 192, 64))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overlay_graphicsView_07.sizePolicy().hasHeightForWidth())
        self.overlay_graphicsView_07.setSizePolicy(sizePolicy)
        self.overlay_graphicsView_07.setMinimumSize(QtCore.QSize(192, 64))
        self.overlay_graphicsView_07.setMaximumSize(QtCore.QSize(192, 64))
        self.overlay_graphicsView_07.setFrameShape(QtGui.QFrame.NoFrame)
        self.overlay_graphicsView_07.setAlignment(QtCore.Qt.AlignCenter)
        self.overlay_graphicsView_07.setObjectName(_fromUtf8("overlay_graphicsView_07"))
        self.overlay_graphicsView_01.raise_()
        self.overlay_radioButton_01.raise_()
        self.overlay_radioButton_02.raise_()
        self.overlay_radioButton_03.raise_()
        self.overlay_radioButton_04.raise_()
        self.corrout_radioButton.raise_()
        self.overlay_radioButton_05.raise_()
        self.overlay_radioButton_06.raise_()
        self.overlay_radioButton_07.raise_()
        self.overlay_radioButton_08.raise_()
        self.overlay_graphicsView_04.raise_()
        self.overlay_graphicsView_06.raise_()
        self.overlay_graphicsView_03.raise_()
        self.overlay_graphicsView_08.raise_()
        self.overlay_graphicsView_05.raise_()
        self.overlay_graphicsView_02.raise_()
        self.overlay_graphicsView_07.raise_()
        self.histogram_groupBox = QtGui.QGroupBox(self.centralwidget)
        self.histogram_groupBox.setGeometry(QtCore.QRect(440, 300, 381, 201))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogram_groupBox.sizePolicy().hasHeightForWidth())
        self.histogram_groupBox.setSizePolicy(sizePolicy)
        self.histogram_groupBox.setMinimumSize(QtCore.QSize(100, 100))
        self.histogram_groupBox.setMaximumSize(QtCore.QSize(500, 1000))
        self.histogram_groupBox.setObjectName(_fromUtf8("histogram_groupBox"))
        self.histogram_graphicsView = GraphicsLayoutWidget(self.histogram_groupBox)
        self.histogram_graphicsView.setGeometry(QtCore.QRect(10, 30, 361, 161))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogram_graphicsView.sizePolicy().hasHeightForWidth())
        self.histogram_graphicsView.setSizePolicy(sizePolicy)
        self.histogram_graphicsView.setMinimumSize(QtCore.QSize(0, 100))
        self.histogram_graphicsView.setMaximumSize(QtCore.QSize(1000, 1000))
        self.histogram_graphicsView.setObjectName(_fromUtf8("histogram_graphicsView"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(830, 300, 281, 201))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 35, 16, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pixnumX_doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.pixnumX_doubleSpinBox.setGeometry(QtCore.QRect(30, 30, 67, 24))
        self.pixnumX_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pixnumX_doubleSpinBox.setDecimals(0)
        self.pixnumX_doubleSpinBox.setObjectName(_fromUtf8("pixnumX_doubleSpinBox"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 56, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.coordX_doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.coordX_doubleSpinBox.setGeometry(QtCore.QRect(100, 30, 67, 24))
        self.coordX_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coordX_doubleSpinBox.setDecimals(3)
        self.coordX_doubleSpinBox.setObjectName(_fromUtf8("coordX_doubleSpinBox"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(100, 20, 56, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.pixnumY_doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.pixnumY_doubleSpinBox.setGeometry(QtCore.QRect(30, 55, 67, 24))
        self.pixnumY_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pixnumY_doubleSpinBox.setDecimals(0)
        self.pixnumY_doubleSpinBox.setObjectName(_fromUtf8("pixnumY_doubleSpinBox"))
        self.coordY_doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.coordY_doubleSpinBox.setGeometry(QtCore.QRect(100, 55, 67, 24))
        self.coordY_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coordY_doubleSpinBox.setDecimals(3)
        self.coordY_doubleSpinBox.setObjectName(_fromUtf8("coordY_doubleSpinBox"))
        self.pixnumZ_doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.pixnumZ_doubleSpinBox.setGeometry(QtCore.QRect(30, 80, 67, 24))
        self.pixnumZ_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pixnumZ_doubleSpinBox.setDecimals(0)
        self.pixnumZ_doubleSpinBox.setObjectName(_fromUtf8("pixnumZ_doubleSpinBox"))
        self.coordZ_doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.coordZ_doubleSpinBox.setGeometry(QtCore.QRect(100, 80, 67, 24))
        self.coordZ_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coordZ_doubleSpinBox.setDecimals(3)
        self.coordZ_doubleSpinBox.setObjectName(_fromUtf8("coordZ_doubleSpinBox"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 16, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 85, 16, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.coordT_doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.coordT_doubleSpinBox.setGeometry(QtCore.QRect(100, 130, 67, 24))
        self.coordT_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coordT_doubleSpinBox.setDecimals(3)
        self.coordT_doubleSpinBox.setObjectName(_fromUtf8("coordT_doubleSpinBox"))
        self.pixnumT_doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.pixnumT_doubleSpinBox.setGeometry(QtCore.QRect(30, 130, 67, 24))
        self.pixnumT_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pixnumT_doubleSpinBox.setDecimals(0)
        self.pixnumT_doubleSpinBox.setObjectName(_fromUtf8("pixnumT_doubleSpinBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 135, 16, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.TimeSlider = QtGui.QSlider(self.groupBox)
        self.TimeSlider.setGeometry(QtCore.QRect(10, 165, 261, 22))
        self.TimeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.TimeSlider.setObjectName(_fromUtf8("TimeSlider"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(30, 120, 56, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(100, 120, 56, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.runMovieButton = QtGui.QPushButton(self.groupBox)
        self.runMovieButton.setGeometry(QtCore.QRect(170, 125, 110, 32))
        self.runMovieButton.setObjectName(_fromUtf8("runMovieButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.histogram_groupBox_2.setTitle(_translate("MainWindow", "Information", None))
        self.imageData_groupBox.setTitle(_translate("MainWindow", "Image Data", None))
        self.label.setText(_translate("MainWindow", "Click in image to position ROI.  Drag right or left to increase or decrease the ROI size", None))
        self.resetDispLimits_Button.setText(_translate("MainWindow", "Full Range", None))
        self.resetDispSmart_Button.setText(_translate("MainWindow", "Smart", None))
        self.saveDisp_Button.setText(_translate("MainWindow", "Save", None))
        self.setMask_Button.setText(_translate("MainWindow", "No mask", None))
        self.label_2.setText(_translate("MainWindow", "Colormap", None))
        self.gray_radioButton.setText(_translate("MainWindow", "Gray", None))
        self.thermal_radioButton.setText(_translate("MainWindow", "Thermal", None))
        self.GYR_radioButton.setText(_translate("MainWindow", "GYR", None))
        self.rainbow_radioButton.setText(_translate("MainWindow", "Rainbow", None))
        self.viridis_radioButton.setText(_translate("MainWindow", "Viridis", None))
        self.jet_radioButton.setText(_translate("MainWindow", "Jet", None))
        self.label_5.setText(_translate("MainWindow", "ASPECTS", None))
        self.aspects_checkBox.setText(_translate("MainWindow", "Average", None))
        self.report_pushButton.setText(_translate("MainWindow", "Report", None))
        self.overlays_groupBox.setTitle(_translate("MainWindow", "Overlays", None))
        self.overlay_radioButton_05.setText(_translate("MainWindow", "Mask", None))
        self.overlay_radioButton_01.setText(_translate("MainWindow", "Lag times", None))
        self.overlay_radioButton_02.setText(_translate("MainWindow", "Correlation strength", None))
        self.overlay_radioButton_03.setText(_translate("MainWindow", "MTT", None))
        self.overlay_radioButton_04.setText(_translate("MainWindow", "R2", None))
        self.corrout_radioButton.setText(_translate("MainWindow", "Correlation function", None))
        self.overlay_radioButton_06.setText(_translate("MainWindow", "Mask", None))
        self.overlay_radioButton_07.setText(_translate("MainWindow", "Mask", None))
        self.overlay_radioButton_08.setText(_translate("MainWindow", "Mask", None))
        self.histogram_groupBox.setTitle(_translate("MainWindow", "Overlay Histogram", None))
        self.groupBox.setTitle(_translate("MainWindow", "Location", None))
        self.label_4.setText(_translate("MainWindow", "X", None))
        self.label_7.setText(_translate("MainWindow", "Voxel", None))
        self.label_9.setText(_translate("MainWindow", "mm", None))
        self.label_6.setText(_translate("MainWindow", "Y", None))
        self.label_8.setText(_translate("MainWindow", "Z", None))
        self.label_3.setText(_translate("MainWindow", "T", None))
        self.label_10.setText(_translate("MainWindow", "Timepoint", None))
        self.label_11.setText(_translate("MainWindow", "seconds", None))
        self.runMovieButton.setText(_translate("MainWindow", "Start Movie", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))

from pyqtgraph import GraphicsLayoutWidget, GraphicsView
